export interface Contact {
  _id: string; // Assuming _id is the unique identifier generated by MongoDB
  user_id: string; // Assuming user_id is a string
  name: string;
  email: string;
  phone: string;
  createdAt: Date; // Assuming timestamps are created by MongoDB
  updatedAt: Date;
}

export interface CreateContact {
  name: string;
  email: string;
  phone: string;
}

export interface UpdateContactProps {
  name: string | undefined;
  email: string | undefined;
  phone: string | undefined;
}
